export default {
  rootDir: './',
  roots: ['<rootDir>'],
  testEnvironment: 'node',
  collectCoverage: true,
  collectCoverageFrom: [
    'controllers/**/*.js',
    'services/**/*.js',
    'middleware/**/*.js',
    'routes/**/*.js',
    'utils/**/*.js',
    'db/**/*.js',
    '!coverage/**',
    '!cli/**',
    '!scripts/**',
    '!server.js',
    '!jest.config.js',
  ],
  transformIgnorePatterns: ['node_modules/jsonwebtoken/'],
  coveragePathIgnorePatterns: ['node_modules/jsonwebtoken/'],
  testPathIgnorePatterns: ['authenticateToken.no-cov.test.js'],
  moduleNameMapper: {
    '^whois-json$': '<rootDir>/__mocks__/whois-json.js',
    '^ssl-checker$': '<rootDir>/__mocks__/ssl-checker.js',
    '^whois$': '<rootDir>/__mocks__/whois.js',
  },
};
