export default {
  rootDir: './',
  roots: ['<rootDir>'],
  testEnvironment: 'node',
  collectCoverage: true,
  collectCoverageFrom: [
    'controllers/**/*.js',
    'services/**/*.js',
    'middleware/**/*.js',
    'routes/**/*.js',
    'utils/**/*.js',
    'db/**/*.js',
    '!coverage/**',
    '!cli/**',
    '!scripts/**',
    '!server.js',
    '!jest.config.js',
  ],
  transformIgnorePatterns: ['node_modules/jsonwebtoken/'],
  coveragePathIgnorePatterns: ['node_modules/jsonwebtoken/'],
  testPathIgnorePatterns: ['authenticateToken.no-cov.test.js'],
};
